<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <RootNamespace>VDS_MFG_Sample</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Platforms>x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Autodesk.Connectivity.WebServices">
      <HintPath>..\..\..\..\..\..\Program Files\Autodesk\Autodesk Vault 2027 SDK\bin\x64\core\Autodesk.Connectivity.WebServices.dll</HintPath>
    </Reference>
    <Reference Include="Autodesk.DataManagement.Client.Framework.Forms">
      <HintPath>..\..\..\..\..\..\Program Files\Autodesk\Autodesk Vault 2027 SDK\bin\x64\core\Autodesk.DataManagement.Client.Framework.Forms.dll</HintPath>
    </Reference>
    <Reference Include="Common">
      <HintPath>..\SDK\VDS\Common.dll</HintPath>
    </Reference>
    <Reference Include="CreateObject">
      <HintPath>..\SDK\VDS\CreateObject.dll</HintPath>
    </Reference>
    <Reference Include="dataStandard.UI">
      <HintPath>..\SDK\VDS\dataStandard.UI.dll</HintPath>
    </Reference>
    <Reference Include="log4net">
      <HintPath>..\SDK\VDS\log4net.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
